apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nodejj
  name: nodejs-api
spec:
  selector:
    matchLabels:
      app: nodejs
  replicas: 1
  template:
    metadata:
      labels:
        app: nodejs
    spec:
      containers:
      - image: gramajo/api-node:latest
        name: nodejs
        ports:
        - containerPort: 3000
          name: http

 
