apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: react
  name: react-api
spec:
  selector:
    matchLabels:
      app: react
  replicas: 1
  template:
    metadata:
      labels:
        app: react
    spec:
      containers:
      - image: gramajo/pagina-we-login:latest
        name: react
        ports:
        - containerPort: 80
          name: http

